### ISSUE TITLE
VRNN Model

### ISSUE THREAD

**Issue by MasaruPutut** [CIA-Oceanix/GeoTrackNet#10]
Hello, 

I want to explore more about your VRNN code. Actually I am not familiar about the Sequential model like RNN or LSTM. But I want to learn about it. 

From what I know we use timestep as a variable of how much we look back to previous sequence right? but i don't find it in your code. Could you explain about it a little or if there is any diagram/architecture about the model that you develop it'll be useful
Because I am a little bit confused because the timesteps for each tracks is not the same right?

And I also want to know what is the output of your VRNN model? 

Thank you

**Comment by duonginspace** [comment]
Hello, 

There are many articles explaining LSTM on the Internet, for example:
https://colah.github.io/posts/2015-08-Understanding-LSTMs/

The original paper of VRNN:
https://arxiv.org/abs/1506.02216

The output of the VRNN is the distributions representing the dynamics of the AIS trajectories.

Good luck in your research!
