### ISSUE TITLE
contrario detection Issues

### ISSUE THREAD

**Issue by MasaruPutut** [CIA-Oceanix/GeoTrackNet#11]
Dear Nguyen, 

I just want to make sure something..
in save_logprob and local_logprob mode, the test set is valid dataset right?
but for the contrario_detection we use test dataset right?

if it's true then I think there's some bug in your code because when I run the contrario I got an error

**Comment by duonginspace** [comment]
Hi, 

We have to run `save_logprob` for both the validation set and the test set (and `local_logprob` for the validation set). 

Can you report the bug? This code works for me.

**Comment by MasaruPutut** [comment]
oh I think, it's because I just run save_logprob for validation set so the file is not found. I will try to run test dataset for save_logprob and report if there is an error

thank you

**Comment by duonginspace** [comment]
Ok, good luck!
