### ISSUE TITLE
Ship type

### ISSUE THREAD

**Issue by MasaruPutut** [CIA-Oceanix/GeoTrackNet#12]
Hi,
Your code and research is really good and I have tried your code to my dataset and it's good.

but actually, the track for different shiptype(cargo, fishing, passenger, etc) is also different right?
I just want to know your opinion. Do you think it is a good idea to add ship type to 4-hot vector(it will be 5-hot vector then)?
or do you think we just should run it separately for each ship type?

what do you think?

I'm really grateful that you always responds to my questions hehe :)
it's great to meet you in this repository

thank you..

**Comment by duonginspace** [comment]
Hello, 

I would train different models for different vessel types.

**Comment by supercrazysam** [comment]
Hi, @MasaruPutut, I heard you successfully used the code on your own dataset.

I have modifed the csv2pkl.py and data_preprocessing.py to produce the 3 pkl data files and 3 corresponding pngs.
In the 3 pngs, I can see filtered tracks in the specified region of interest.

But I am not sure what is the next steps. 
What did you do to make it work with your dataset?

What files and what part did you modified?
Are there any things that I need to pay attention to?
Do I need to make the region size (LAT_RANGE, LON_RANGE) on my dataset+pkl,  the same as the default trained model?

**Comment by MasaruPutut** [comment]
Hy @supercrazysam 
after you have 3 pkl files from preprocessing. you need to "calculate_mean" of the training dataset before you run the training code.
after you have the mean.pkl just run the training, then save_logprob(for valid and test dataset), local_logprob(for valid dataset) and contrario_detection(for test dataset).

the thing you have to pay attention is in "calculate_mean.py" the lon_bins, lat_bins, sog_bins, and cog_bins is defined hard coded. but in flag_config.py the authors calculate it by ratio of the ROI compared to the grid resolution that wanted (in this code the resolution of lat and lon id 0.01). 

So I think you should make the lat_bins and lon_bins on "calculate_mean.py" to be a ratio too

Sorry for the late reply. hope this can help you..
have a good research

**Comment by MasaruPutut** [comment]
oh @dnguyengithub I forgot to thank the super authors. really, you helped me a lot. thanks man

**Comment by duonginspace** [comment]
You're welcome. 
Good luck with your research
