### ISSUE TITLE
Dataset Details

### ISSUE THREAD

**Issue by saraaun** [CIA-Oceanix/GeoTrackNet#14]
Hi,

Your IEEE brings me here (really well-written by the way ). I am new to the topic but really would love to repicate your work to gain more understanding. Let start with the datasets:
1. You mentioned that you used 2 datasets: the Gulf of Mexico and the Brittany coast datasets. 
   1.1 For the Gulf of Mexico downloaded from https://marinecadastre.gov/ais/. I have followed the link but there are 19 zones. Where should I start to get the same dataset you used in the paper?
   1.2 For the Brittany datasets: I have contacted G. Hajduch, ghajduch@groupcls.com a few weeks ago for the full dataset, but no response from him. Could you assist me on this matter?

After obtaining the datasets, I may have more questions and hope you would not mind me asking you again in the future.

Thank you!

SW

**Comment by saraaun** [comment]
Just wanted to update that I have just received the Brittany dataset from Prof. Hajduch today :).
.

**Comment by duonginspace** [comment]
Hi @saraaun ,

> For the Gulf of Mexico downloaded from https://marinecadastre.gov/ais/. I have followed the link but there are 19 zones. Where should I start to get the same dataset you used in the paper?

The zone that I used in the paper: lat_min, lat_max, lon_min, lon_mat = 26.5, 30.0, -97.5, -87. 

> Just wanted to update that I have just received the Brittany dataset from Prof. Hajduch today :).

Great!

You can use your own way to preprocess the data. GeoTrackNet needs (lat, lon, sog, cog, timestamp, mmsi) as the inputs.

Good luck!

**Comment by saraaun** [comment]
Hi, the dataset Proj.Hajduch sent is not the one you used in the GeoTracker, unfortunately. I have written to him again and hopefully this time I will get the right one.

Meanwhile, I will start working on another dataset I have in hand right now.

May I ask how you specified/labelled the discovered anomalities? Did you have to send the abnomal tracks to a domain expert and let them do the job for you? Another question is can we generate the abnormal data somehow and use them to verify our methods?
