### ISSUE TITLE
Environment setup difficulties

### ISSUE THREAD

**Issue by RobertSellers** [CIA-Oceanix/GeoTrackNet#2]
Any docker images / conda documentation for creating a suitable environment? I'm currently trying to hack apart the yaml file, and I've only attained partial success using the following docker image tensorflow/tensorflow:1.12.0-py3 with the training portion.  Tips would be appreciated!

**Comment by duonginspace** [comment]
Hi, 
You can create an Anaconda env using the yml file.
`conda env create -f requirements. yml`
See details [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)
Please update your Conda to version 4.8.3 (metapackage 2020.02) to avoid unexpected packages conflicts.

**Comment by RobertSellers** [comment]
Hi. Thank you. Yes, I have tried the conda envioronment on Linux/Windows machines and with v 4.8.3 and I've been able to run the training tool with success with the PY3GPU environment, but I've had to remove some libs to pip to get this working BUT I'm still unable to run the save_logprob line with your example data.

`C:\miniconda\envs\PY3GPU\lib\site-packages\tensorflow\python\util\tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
Traceback (most recent call last):
  File "geotracknet.py", line 54, in <module>
    from flags_config import config
  File "C:\repositories\GeoTrackNet\flags_config.py", line 196, in <module>
    config.onehot_lat_bins = math.ceil((config.lat_max-config.lat_min)/config.onehot_lat_reso)
  File "C:\miniconda\envs\PY3GPU\lib\site-packages\tensorflow\python\platform\flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "C:\miniconda\envs\PY3GPU\lib\site-packages\absl\flags\_flagvalues.py", line 633, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'test_name'`

**Comment by RobertSellers** [comment]
I just confirmed that the conda requirements load "fine" on an ubuntu 20 anaconda install, but I'm getting the exact same error listed above.

**Comment by RobertSellers** [comment]
Ok well, it looks like you've just got a syntax error in your documentation. test_name should just be testset_name.

python geotracknet.py \
  --mode=save_logprob \
  --dataset_dir=./data 
  --trainingset_name=ct_2017010203_10_20/ct_2017010203_10_20_train.pkl \
  --**test_name**=ct_2017010203_10_20/ct_2017010203_10_20_valid.pkl \

**Comment by duonginspace** [comment]
Hi, thank you very much for letting me know. I will update the readme.
