### ISSUE TITLE
Inputs for csv2pkl.py

### ISSUE THREAD

**Issue by Tata17** [CIA-Oceanix/GeoTrackNet#7]
Hello!

I already ran your preprocessed data for the Embedding layer, save_logprob, local_logprob, and contrario_detection. Ran through some issues but I got it to work.

Now, I am trying to run my own dataset. I believe I have to run the csv2pkl.py and datasetpreprocessing.py. I have questions trying to use csv2pkl.py with my data:

1. I don't have ROT, or Nav_stt. Do I need them for the analysis? The paper doesn't mention those as the pillar of the analysis.
2. What does D2C stands for? I also don't have it...
3. line 195:  Where the CARGO_TANKER_ONLY Boolean variable came from?
4. If I want to keep the fishing vessels for the analysis (Cargo, Tanker, and Fishing), should I be executing this block of code with this variable (from Question 3)?
5. Just to make sure, the "LOADING CSV FILES" section, its purpose is to load the data and assign the data type to each column?
6. line 244: Dividing unix time by 1000. Is that specific of your dataset or should also include it?

Thanks in advance for any time that you could spare to help me with these questions.

**Comment by duonginspace** [comment]
Hi Tata17,

First of all, I acknowledge that the preprocessing part (which is not the main point of the method presented in the papers) was poorly written. I wrote this part in a _get things done as fast as possible_ fashion. The two files `csv2pkl.py` and `datasetpreprocessing.py` can surely be optimised, using panda for example.

1. No, we dont use ROT and Nav_stt in this version. You can set those attributes to zeros.
2. D2C stands for "Distance to Coast" = the distance to the nearest coastline. You may not need this attribute. (we tested GeoTrackNet in some regions containing busy ports (not reported in the paper), the D2C was used to remove AIS msgs near the coast).
3. CARGO_TANKER_ONLY a predined flag, CARGO_TANKER_ONLY=True means we apply the model on cargos and tankers only.
4. You should set CARGO_TANKER_ONLY = False.
5. Yes, I suggest using panda if you want to optimise the code.
6. Yes, the UNIX_TIME format of our data is XXXXXXXXXX000. If you are using the standard UNIX_TIME format (XXXXXXXXXX), just ignore this line.

Good luck with your tests!

**Comment by Tata17** [comment]
Very kind to take the time to answer all of the questions, your response was very useful. 

Indeed, currently using Pandas to accommodate my dataset to `csv2pkl.py` and `datasetpreprocessing.py`

thank you and good luck with your work!

**Comment by MasaruPutut** [comment]
Hello! 
I have tried the csv2pkl and it works, but when I try to calculate the mean of the lat, lon, cog, and sog there's an error like this

`Traceback (most recent call last):
  File "calculate_AIS_mean.py", line 90, in <module>
    current_sparse_matrix,_,_ = sparse_AIS_to_dense(tmp,0,0)
  File "calculate_AIS_mean.py", line 60, in sparse_AIS_to_dense
    cog_bins = COG_BINS))
  File "calculate_AIS_mean.py", line 48, in create_dense_vect
    dense_vect[int(lat*lat_bins)] = 1.0
IndexError: index -1219 is out of bounds for axis 0 with size 602`

do you have any idea to solve this? I think it's realted to LAT_BINS, LON_BINS, etc I also curious how to define the LAT_BINS, LON_BINS, et? 

Thank you..
