### ISSUE TITLE
LAT_MIN, LAT_MAX, LON_MIN, LON_MAX Values

### ISSUE THREAD

**Issue by MasaruPutut** [CIA-Oceanix/GeoTrackNet#8]
I'm sorry I'm just confused about the value of LAT_MIN, LAT_MAX, LON_MIN, LON_MAX and SPEED_MAX
Where do you get it from? is it from the dataset or you just initialize it as boundaries of the project?
Thank you

**Comment by duonginspace** [comment]
Hi. 
They are the boundery of the ROI.
